name: Pull request workflow
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  foldersChanged:
    runs-on: ubuntu-20.04
    steps:
     - id: file_changes
       uses: trilom/file-changes-action@1.2.4

     - name: Get folders
       id: folders
       run: |
        content=$(jq ".[]" $HOME/files.json | grep ".tf" | sed 's/\/[^/]*$/\//' |  sed -e 's/^"//' -e 's/"$//' | grep -v '\..*' | uniq | jq -R -s -c 'split("\n")[:-1]')
        echo "::set-output name=folders::$content"
    outputs:
      folders: ${{ steps.folders.outputs.folders }}

  fmt:
    runs-on: ubuntu-20.04
    needs: foldersChanged
    name: fmt
    if: ${{ needs.foldersChanged.outputs.folders != '[]' && needs.foldersChanged.outputs.folders != '' }}
    strategy:
      matrix:
        folder: ${{ fromJson(needs.foldersChanged.outputs.folders) }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - uses: hashicorp/setup-terraform@v1
        name: setup terraform
        with:
          terraform_version: 1.0.8

      - name: run terraform fmt
        run: |
          cd ${{ matrix.folder }}
          terraform fmt -check=true -diff
  